%let workhere=C:\Users\Donald Murray\OneDrive - Smarter Balanced UCSC\IA_Calib\1819;
libname libHere "&workhere.";

/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Thursday, October 17, 2019 at 12:44:58 AM
   By task:     Import Data Wizard
   
   Source file: C:\Users\Donald Murray\OneDrive - Smarter Balanced
   UCSC\IA_Calib\1819\ItemId_itemType.csv
   Server:      Local File System
   
   Output data: LIBHERE.ItemId_itemType
   Server:      Local
   -------------------------------------------------------------------- */
%SetDSLabel;
DATA LIBHERE.ItemId_itemType (compress=yes label="&DSLabel.");
    LENGTH
        itemid             8
        itemtype         $ 4 ;
    FORMAT
        itemid           BEST6.
        itemtype         $CHAR4. ;
    INFORMAT
        itemid           BEST6.
        itemtype         $CHAR4. ;
    INFILE "&workhere.\ItemId_itemType.csv"
        LRECL=32767
        FIRSTOBS=2
        ENCODING="WLATIN1"
        DLM='2c'x
        MISSOVER
        DSD ;
    INPUT
        itemid           : ?? BEST6.
        itemtype         : $CHAR4. ;
RUN;

/*	Now Write out the python dictionary construct	*/
data _null_;
	file "&workhere.\ItemIdItemType.py";
	set libhere.itemid_itemtype end=lastone;
	format outlyn $64.;
	if _n_=1 then do;
		outlyn = 'itype = {';
		put outlyn;
	end;
	if lastone then do;
		outlyn =  "'"||trim(left(itemid))||"' : '"||trim(itemtype)||"'}";
		put outlyn;
	end;
	else do;
		outlyn = "'"||trim(left(itemid))||"' : '"||trim(itemtype)||"',";
		put outlyn;
	end;
run;