/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Tuesday, April 21, 2020 at 8:40:45 AM
   By task:     Import Data Wizard
   
   Source file: E:\SBAC\AnnualStudTest\1819\DRC\NV\Smarter_No_PII.csv
   Server:      Local File System
   
   Output data: LIBHERE.Smarter_No_PII
   Server:      Local
   -------------------------------------------------------------------- */

%macro NVFldFmtLst;
	report_dist_num  $CHAR2.
	report_dist_name $CHAR40.
	report_sch_num   $CHAR5.
	report_sch_name  $CHAR50.
	precode_dist_num $CHAR2.
	precode_sch_num  $CHAR5.
	last             $CHAR1.
	first            $CHAR1.
	middle           $CHAR1.
	dob              $CHAR1.
	state_unique_id  BEST10.
	local_student_id $CHAR1.
	student_id       $CHAR1.
	gender           $CHAR1.
	ethnicity        $CHAR1.
	iep              BEST1.
	lep              BEST1.
	f_lep_lte        BEST1.
	frl              BEST1.
	immigrant        BEST1.
	migrant          BEST1.
	nic              BEST1.
	yid              BEST1.
	yis              BEST1.
	slug_key         BEST7.
	homeschool       BEST1.
	nic_y2           BEST1.
	foster_care      BEST1.
	armed_forces     BEST1.
	homeless         BEST1.
	precode_grade_level BEST2.
	grade_level      BEST2.
	test_date_start  MMDDYY10.
	test_date_end    MMDDYY10.
	school_year      BEST4.
	%macro WrapBySbj(Sbj);
		&Sbj._test_sch_num_CAT $CHAR5.
		&Sbj._test_sch_num_PT $CHAR5.
		&Sbj._lithocode_CAT BEST12.
		&Sbj._lithocode_PT BEST12.
		&Sbj._iep_accommodation $CHAR1.
		&Sbj._braille	BEST1.
		&Sbj._large_print  BEST1.
		&Sbj._pod		BEST1.
		&Sbj._text_to_speech_items BEST1.
		&Sbj._video_sign_language BEST1.
		&Sbj._speech_to_text BEST1.
		&Sbj._cat_test_start_date_time DATETIME18.
		&Sbj._cat_test_submit_date_time DATETIME18.
		&Sbj._tc_modification_CAT $CHAR3.
		&Sbj._tc_modification_PT $CHAR3.
		&Sbj._tc_invalidation_CAT $CHAR3.
		&Sbj._tc_invalidation_PT $CHAR3.
		&Sbj._did_not_participate_CAT $CHAR3.
		&Sbj._did_not_participate_PT $CHAR3.
		&Sbj._participation_status BEST1.
		&Sbj._attemptedness_status BEST1.
		&Sbj._test_form_CAT $CHAR3.
		&Sbj._test_form_PT $CHAR3.
		&Sbj._CAT_number_attempted BEST2.
		&Sbj._PT_number_attempted BEST1.
		&Sbj._scale_score  BEST4.
		&Sbj._achievement_level BEST1.
		&Sbj._sem_high     BEST4.
		&Sbj._sem_low      BEST4.
		&Sbj._sem_value    BEST3.
		&Sbj._proficient   $CHAR14.
		&Sbj._C1_performance_level BEST1.
		&Sbj._C3_performance_level BEST1.
		&Sbj._C4_performance_level BEST1.
		&Sbj._PT_score_string $CHAR20.
		&Sbj._CAT_score_string $CHAR50.
		&Sbj._CAT_item_id_string $300.
	%mend WrapBySbj;
		%WrapBySbj(ela)
		%WrapBySbj(math)
	ela_text_to_speech_itemsandpassa BEST1.
	ela_pt_part1_start_date_time DATETIME18.
	ela_pt_part1_submit_date_time DATETIME18.
	ela_pt_part2_start_date_time DATETIME18.
	ela_pt_part2_submit_date_time DATETIME18.
	ela_C2_performance_level BEST1.
	ela_lexile_score $CHAR6.
	math_pt_start_date_time DATETIME18.
	math_pt_submit_date_time DATETIME18.
	math_quantile_score $CHAR6.
%mend NVFldFmtLst;

%macro ReadNVStud(infyl, outDS);
	%SetDSLabel
	DATA &outDS. (compress=yes label="&DSLabel.") ;
		LENGTH
			report_dist_num  $ 2
			report_dist_name $ 40
			report_sch_num   $ 5
			report_sch_name  $ 50
			precode_dist_num $ 2
			precode_sch_num  $ 5
			last             $ 1
			first            $ 1
			middle           $ 1
			dob              $ 1
			state_unique_id    8
			local_student_id $ 1
			student_id       $ 1
			gender           $ 1
			ethnicity        $ 1
			iep                8
			lep                8
			f_lep_lte          8
			frl                8
			immigrant          8
			migrant            8
			nic                8
			yid                8
			yis                8
			slug_key           8
			homeschool         8
			nic_y2             8
			foster_care        8
			armed_forces       8
			homeless           8
			precode_grade_level   8
			grade_level        8
			test_date_start    8
			test_date_end      8
			school_year        8
			%macro WrapBySbj4L(Sbj);
				&Sbj._test_sch_num_CAT $ 5
				&Sbj._test_sch_num_PT $ 5
				&Sbj._lithocode_CAT 8
				&Sbj._lithocode_PT 8
				&Sbj._iep_accommodation $ 1
				&Sbj._braille 8
				&Sbj._large_print 8
				&Sbj._pod 8
				&Sbj._text_to_speech_items 8
				&Sbj._video_sign_language 8
				&Sbj._speech_to_text 8
				&Sbj._cat_test_start_date_time 8
				&Sbj._cat_test_submit_date_time 8
				&Sbj._tc_modification_CAT $ 3
				&Sbj._tc_modification_PT $ 3
				&Sbj._tc_invalidation_CAT $ 3
				&Sbj._tc_invalidation_PT $ 3
				&Sbj._did_not_participate_CAT $ 3
				&Sbj._did_not_participate_PT $ 3
				&Sbj._participation_status 8
				&Sbj._attemptedness_status 8
				&Sbj._test_form_CAT $ 3
				&Sbj._test_form_PT $ 3
				&Sbj._CAT_number_attempted 8
				&Sbj._PT_number_attempted 8
				&Sbj._scale_score 8
				&Sbj._achievement_level 8
				&Sbj._sem_high 8
				&Sbj._sem_low 8
				&Sbj._sem_value 8
				&Sbj._proficient $ 14
				&Sbj._C1_performance_level 8
				&Sbj._C3_performance_level 8
				&Sbj._C4_performance_level 8
				&Sbj._PT_score_string $ 20
				&Sbj._CAT_score_string $ 50
				&Sbj._CAT_item_id_string $ 300
			%mend WrapBySbj4L;
				%WrapBySbj4L(ela)
				%WrapBySbj4L(math)
			ela_text_to_speech_itemsandpassa   8
			ela_pt_part1_start_date_time   8
			ela_pt_part1_submit_date_time   8
			ela_pt_part2_start_date_time   8
			ela_pt_part2_submit_date_time   8
			ela_C2_performance_level   8
			ela_lexile_score $ 6
			math_pt_start_date_time   8
			math_pt_submit_date_time   8
			math_quantile_score $ 6 ;
		LABEL
			ela_text_to_speech_itemsandpassa = "ela_text_to_speech_itemsandpassages" ;
		FORMAT %NVFldFmtLst;
		INFORMAT %NVFldFmtLst;
		INFILE "&infyl." LRECL=32767 FIRSTOBS=2
			ENCODING="WLATIN1" DLM='2c'x MISSOVER DSD ;
		INPUT
			report_dist_num  : $CHAR2.
			report_dist_name : $CHAR40.
			report_sch_num   : $CHAR5.
			report_sch_name  : $CHAR50.
			precode_dist_num : $CHAR2.
			precode_sch_num  : $CHAR5.
			last             : $CHAR1.
			first            : $CHAR1.
			middle           : $CHAR1.
			dob              : $CHAR1.
			state_unique_id  : ?? BEST10.
			local_student_id : $CHAR1.
			student_id       : $CHAR1.
			gender           : $CHAR1.
			ethnicity        : $CHAR1.
			iep              : ?? BEST1.
			lep              : ?? BEST1.
			f_lep_lte        : ?? BEST1.
			frl              : ?? BEST1.
			immigrant        : ?? BEST1.
			migrant          : ?? BEST1.
			nic              : ?? BEST1.
			yid              : ?? BEST1.
			yis              : ?? BEST1.
			slug_key         : ?? BEST7.
			homeschool       : ?? BEST1.
			nic_y2           : ?? BEST1.
			foster_care      : ?? BEST1.
			armed_forces     : ?? BEST1.
			homeless         : ?? BEST1.
			precode_grade_level : ?? BEST2.
			grade_level      : ?? BEST2.
			test_date_start  : ?? MMDDYY8.
			test_date_end    : ?? MMDDYY8.
			school_year      : ?? BEST4.
			ela_test_sch_num_CAT : $CHAR5.
			ela_test_sch_num_PT : $CHAR5.
			ela_lithocode_CAT : ?? BEST12.
			ela_lithocode_PT : ?? BEST12.
			ela_iep_accommodation : $CHAR1.
			ela_braille      : ?? BEST1.
			ela_large_print  : ?? BEST1.
			ela_pod          : ?? BEST1.
			ela_text_to_speech_items : ?? BEST1.
			ela_text_to_speech_itemsandpassa : ?? BEST1.
			ela_video_sign_language : ?? BEST1.
			ela_speech_to_text : ?? BEST1.
			ela_pt_part1_start_date_time : ?? ANYDTDTM19.
			ela_pt_part1_submit_date_time : ?? ANYDTDTM19.
			ela_pt_part2_start_date_time : ?? ANYDTDTM19.
			ela_pt_part2_submit_date_time : ?? ANYDTDTM19.
			ela_cat_test_start_date_time : ?? ANYDTDTM19.
			ela_cat_test_submit_date_time : ?? ANYDTDTM19.
			ela_tc_modification_CAT : $CHAR3.
			ela_tc_modification_PT : $CHAR3.
			ela_tc_invalidation_CAT : $CHAR3.
			ela_tc_invalidation_PT : $CHAR3.
			ela_did_not_participate_CAT : $CHAR3.
			ela_did_not_participate_PT : $CHAR3.
			ela_participation_status : ?? BEST1.
			ela_attemptedness_status : ?? BEST1.
			ela_test_form_CAT : $CHAR3.
			ela_test_form_PT : $CHAR3.
			ela_CAT_number_attempted : ?? BEST2.
			ela_PT_number_attempted : ?? BEST1.
			ela_scale_score  : ?? BEST4.
			ela_achievement_level : ?? BEST1.
			ela_sem_high     : ?? BEST4.
			ela_sem_low      : ?? BEST4.
			ela_sem_value    : ?? BEST3.
			ela_proficient   : $CHAR14.
			ela_C1_performance_level : ?? BEST1.
			ela_C2_performance_level : ?? BEST1.
			ela_C3_performance_level : ?? BEST1.
			ela_C4_performance_level : ?? BEST1.
			ela_lexile_score : $CHAR6.
			ela_PT_score_string : $CHAR20.
			ela_CAT_score_string : $CHAR50.
			ela_CAT_item_id_string $
			math_test_sch_num_CAT : $CHAR5.
			math_test_sch_num_PT : $CHAR5.
			math_lithocode_CAT : ?? BEST12.
			math_lithocode_PT : ?? BEST12.
			math_iep_accommodation : $CHAR1.
			math_braille     : ?? BEST1.
			math_large_print : ?? BEST1.
			math_pod         : ?? BEST1.
			math_text_to_speech_items : ?? BEST1.
			math_video_sign_language : ?? BEST1.
			math_speech_to_text : ?? BEST1.
			math_pt_start_date_time : ?? ANYDTDTM19.
			math_pt_submit_date_time : ?? ANYDTDTM19.
			math_cat_test_start_date_time : ?? ANYDTDTM19.
			math_cat_test_submit_date_time : ?? ANYDTDTM19.
			math_tc_modification_CAT : $CHAR3.
			math_tc_modification_PT : $CHAR3.
			math_tc_invalidation_CAT : $CHAR3.
			math_tc_invalidation_PT : $CHAR3.
			math_did_not_participate_CAT : $CHAR3.
			math_did_not_participate_PT : $CHAR3.
			math_participation_status : ?? BEST1.
			math_attemptedness_status : ?? BEST1.
			math_test_form_CAT : $CHAR3.
			math_test_form_PT : $CHAR3.
			math_CAT_number_attempted : ?? BEST2.
			math_PT_number_attempted : ?? BEST1.
			math_scale_score : ?? BEST4.
			math_achievement_level : ?? BEST1.
			math_sem_high    : ?? BEST4.
			math_sem_low     : ?? BEST4.
			math_sem_value   : ?? BEST3.
			math_proficient  : $CHAR14.
			math_C1_performance_level : ?? BEST1.
			math_C3_performance_level : ?? BEST1.
			math_C4_performance_level : ?? BEST1.
			math_quantile_score : $CHAR6.
			math_PT_score_string : $CHAR20.
			math_CAT_score_string : $CHAR50.
			math_CAT_item_id_string $ ;
	RUN;
%mend ReadNVStud;

%macro NVCLFldFmtLst;
	Grade $2.	Subject $4.	Claims $2.	Scale_Score 4.0		SEM 3.0
	Upper_SEM 4.0		Lower_SEM 4.0		Slug_key 8.0
	lithocode_CAT 12.0 lithocode_PT 12.0 
%mend NVCLFldFmtLst;

%macro ReadNVClaims(inCfyl, outCDS);
	%SetDSLabel;
	data &outCDS. (compress=yes label="&DSLabel.");
		length 
			Grade $ 2		Subject $ 4		Claims $ 2 
			Scale_Score 8		SEM 8
			Upper_SEM 8		Lower_SEM 8
			Slug_key 8		lithocode_CAT 8 lithocode_PT 8 ;
		format %NVCLFldFmtLst;
		informat %NVCLFldFmtLst;
		INFILE "&inCfyl." LRECL=128 FIRSTOBS=2
			ENCODING="WLATIN1" DLM='2c'x MISSOVER DSD ;
		input Grade $  Subject $  Claims $
			Scale_Score  SEM  Upper_SEM  Lower_SEM
			Slug_key  lithocode_CAT  lithocode_PT;
	run;
%mend ReadNVClaims;