/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Friday, December 27, 2019 at 11:37:55 AM
   By task:     Import Data Wizard
   
   Source file:
   E:\SBAC\AnnualStudTest\1819\AIR\HI\G3ThroughG11_ELA_ProductionExami
   nee_20191007163023.txt
   Server:      Local File System
   
   Output data: LIBHERE.HI_ELA_Stud_1819
   Server:      Local
   -------------------------------------------------------------------- */

%macro StudVarFmtLst;
	SchoolYear       BEST4.
	StudentIdentifier $CHAR43.
	Sex	      $CHAR6.
	HispanicOrLatinoEthnicity $CHAR3.
	AmericanIndianOrAlaskaNative $CHAR3.	
	Asian            $CHAR3.
	BlackOrAfricanAmerican $CHAR3.
	White            $CHAR3.
	NativeHawaiianOrOtherPacificIsla $CHAR3.
	DemographicRaceTwoOrMoreRaces $CHAR3.
	IDEAIndicator    $CHAR3.
	LEPStatus        $CHAR3.
	Section504Status $CHAR22.
	EconomicDisadvantageStatus $CHAR3.
	ResponsibleDistrictIdentifier $CHAR12.
	ResponsibleSchoolIdentifier $CHAR24.
	GradeLevelWhenAssessed BEST2.
	GradeLevelWhenReported BEST2.
	AssessmentSubtestResultDateCreat $CHAR16.
	AssessmentAcademicSubject BEST5.
	AssessmentLevelForWhichDesigned BEST2.
	AssessmentSubtestTitle $CHAR65.
	AssessmentSubtestIdentifier $CHAR42.
	TestStatus       $CHAR11.
	TestMode         $CHAR1.
	AssessmentSessionActualStartDate $CHAR16.
	AssessmentSessionActualEndDateTi $CHAR16.
	VndrTstEvent_ID  BEST8.
	AssessmentAccommodation $CHAR4999.
	TotNbrPaused     BEST2.
	NbrPauseRet      BEST2.
	Oprtnty          BEST1.
	LanguageCode     $CHAR3.
	EnglishLanguageProficiencyLevel $CHAR1.
	MigrantStatus    $CHAR3.
	FirstEntryDateIntoUSSchool $CHAR10.
	LimitedEnglishProficiencyEntryDa $CHAR10.
	LEPExitDate      $CHAR10.
	TitleIIILanguageInstructionProgr $CHAR27.
	PrimaryDisabilityType $CHAR3.
	TestMonitorUserID $CHAR31.
	TestMonitorSessionID $CHAR14.
	TestMonitorEmailAddress $CHAR48.
	Num_Itms_TOT     BEST2.
	AssessmentNumberOfItems BEST2.
	THETA_TOT        BEST7.
	SEM_TOT_THETA    BEST6.
	SS_TOT           BEST4.
	SEM_TOTSS        BEST3.
	Performance_Level BEST1.
	AttemptednessIndicator $CHAR1.
	Label_SRC1       $CHAR4.
	Num_Itms_SRC1    BEST2.
	THETA_SRC1       BEST7.
	SEM_THETA_SRC1   BEST6.
	SS_SRC1          BEST4.
	SEM_SRC1         BEST3.
	PL_SRC1          BEST1.
	Label_SRC2       $CHAR4.
	Num_Itms_SRC2    BEST1.
	THETA_SRC2       BEST7.
	SEM_THETA_SRC2   BEST6.
	SS_SRC2          BEST4.
	SEM_SRC2         BEST3.
	PL_SRC2          BEST1.
	Label_SRC3       $CHAR4.
	Num_Itms_SRC3    BEST1.
	THETA_SRC3       BEST7.
	SEM_THETA_SRC3   BEST6.
	SS_SRC3          BEST4.
	SEM_SRC3         BEST3.
	PL_SRC3          BEST1.
	Label_SRC4       $CHAR4.
	Num_Itms_SRC4    BEST1.
	THETA_SRC4       BEST7.
	SEM_THETA_SRC4   BEST6.
	SS_SRC4          BEST4.
	SEM_SRC4         BEST3.
	PL_SRC4          BEST1.
	Label_SRC5       $CHAR1.
	Num_Itms_SRC5    $CHAR1.
	THETA_SRC5       $CHAR1.
	SEM_THETA_SRC5   $CHAR1.
	SS_SRC5          $CHAR1.
	SEM_SRC5         $CHAR1.
	PL_SRC5          $CHAR1.
	Label_SRC6       $CHAR1.
	Num_Itms_SRC6    $CHAR1.
	THETA_SRC6       $CHAR1.
	SEM_THETA_SRC6   $CHAR1.
	SS_SRC6          $CHAR1.
	SEM_SRC6         $CHAR1.
	PL_SRC6          $CHAR1.
	Paper_Barcode    $CHAR15.
	SegmentID1       $CHAR100.
	Accommodations_Segment1 $CHAR1000.
	SegmentID2       $CHAR100.
	Accommodations_Segment2 $CHAR1000.
	SegmentID3       $CHAR100.
	Accommodations_Segment3 $CHAR1000.
	OppKey           $CHAR36.
%mend StudVarFmtLst;

%macro ReadAIRStud(ST, Subj, FylNm, outDS, encdng);
	%SetDSLabel;
	DATA &outDS. (compress=yes label="&DSLabel.");
    LENGTH
        SchoolYear         8
        StudentIdentifier $ 43
        Sex              $ 6
        HispanicOrLatinoEthnicity $ 3
        AmericanIndianOrAlaskaNative $ 3
        Asian            $ 3
        BlackOrAfricanAmerican $ 3
        White            $ 3
        NativeHawaiianOrOtherPacificIsla $ 3
        DemographicRaceTwoOrMoreRaces $ 3
        IDEAIndicator    $ 3
        LEPStatus        $ 3
        Section504Status $ 22
        EconomicDisadvantageStatus $ 3
        ResponsibleDistrictIdentifier  $ 12
        ResponsibleSchoolIdentifier   $ 24
        GradeLevelWhenAssessed   8
        GradeLevelWhenReported   8
        AssessmentSubtestResultDateCreat $ 16
        AssessmentAcademicSubject   8
        AssessmentLevelForWhichDesigned   8
        AssessmentSubtestTitle $ 65
        AssessmentSubtestIdentifier $ 42
        TestStatus       $ 11
        TestMode         $ 1
        AssessmentSessionActualStartDate  $ 16
        AssessmentSessionActualEndDateTi  $ 16
        VndrTstEvent_ID    8
        AssessmentAccommodation $ 4999
        TotNbrPaused       8
        NbrPauseRet        8
        Oprtnty            8
        LanguageCode     $ 3
        EnglishLanguageProficiencyLevel $ 1
        MigrantStatus    $ 3
        FirstEntryDateIntoUSSchool $ 10
        LimitedEnglishProficiencyEntryDa $ 10
        LEPExitDate      $ 10
        TitleIIILanguageInstructionProgr $ 27
        PrimaryDisabilityType $ 3
        TestMonitorUserID $ 31
        TestMonitorSessionID $ 14
        TestMonitorEmailAddress $ 48
        Num_Itms_TOT       8
        AssessmentNumberOfItems   8
        THETA_TOT          8
        SEM_TOT_THETA      8
        SS_TOT             8
        SEM_TOTSS          8
        Performance_Level   8
        AttemptednessIndicator $ 1
        Label_SRC1       $ 4
        Num_Itms_SRC1      8
        THETA_SRC1         8
        SEM_THETA_SRC1     8
        SS_SRC1            8
        SEM_SRC1           8
        PL_SRC1            8
        Label_SRC2       $ 4
        Num_Itms_SRC2      8
        THETA_SRC2         8
        SEM_THETA_SRC2     8
        SS_SRC2            8
        SEM_SRC2           8
        PL_SRC2            8
        Label_SRC3       $ 4
        Num_Itms_SRC3      8
        THETA_SRC3         8
        SEM_THETA_SRC3     8
        SS_SRC3            8
        SEM_SRC3           8
        PL_SRC3            8
        Label_SRC4       $ 4
        Num_Itms_SRC4      8
        THETA_SRC4         8
        SEM_THETA_SRC4     8
        SS_SRC4            8
        SEM_SRC4           8
        PL_SRC4            8
        Label_SRC5       $ 1
        Num_Itms_SRC5    $ 1
        THETA_SRC5       $ 1
        SEM_THETA_SRC5   $ 1
        SS_SRC5          $ 1
        SEM_SRC5         $ 1
        PL_SRC5          $ 1
        Label_SRC6       $ 1
        Num_Itms_SRC6    $ 1
        THETA_SRC6       $ 1
        SEM_THETA_SRC6   $ 1
        SS_SRC6          $ 1
        SEM_SRC6         $ 1
        PL_SRC6          $ 1
        Paper_Barcode    $ 15
        SegmentID1       $ 100
        Accommodations_Segment1 $ 1000
        SegmentID2       $ 100
        Accommodations_Segment2 $ 1000
        SegmentID3       $ 100
        Accommodations_Segment3 $ 1000
        OppKey           $ 36 ;
    LABEL
        NativeHawaiianOrOtherPacificIsla = "NativeHawaiianOrOtherPacificIslander"
        AssessmentSubtestResultDateCreat = "AssessmentSubtestResultDateCreated"
        AssessmentSessionActualStartDate = "AssessmentSessionActualStartDateTime"
        AssessmentSessionActualEndDateTi = "AssessmentSessionActualEndDateTime"
        LimitedEnglishProficiencyEntryDa = "LimitedEnglishProficiencyEntryDate"
        TitleIIILanguageInstructionProgr = "TitleIIILanguageInstructionProgramType" ;
    FORMAT %StudVarFmtLst;
    INFORMAT %StudVarFmtLst;
    INFILE "&FylNm."
        LRECL=32767
        FIRSTOBS=2
        ENCODING="&encdng."
        DLM='7c'x
        MISSOVER
        DSD ;
    INPUT
        SchoolYear       : ?? BEST4.
        StudentIdentifier : $CHAR43.
        Sex              : $CHAR6.
        HispanicOrLatinoEthnicity : $CHAR3.
        AmericanIndianOrAlaskaNative : $CHAR3.
        Asian            : $CHAR3.
        BlackOrAfricanAmerican : $CHAR3.
        White            : $CHAR3.
        NativeHawaiianOrOtherPacificIsla : $CHAR3.
        DemographicRaceTwoOrMoreRaces : $CHAR3.
        IDEAIndicator    : $CHAR3.
        LEPStatus        : $CHAR3.
        Section504Status : $CHAR22.
        EconomicDisadvantageStatus : $CHAR3.
        ResponsibleDistrictIdentifier : $CHAR12.
        ResponsibleSchoolIdentifier : $CHAR24.
        GradeLevelWhenAssessed : ?? BEST2.
        GradeLevelWhenReported : ?? BEST2.
        AssessmentSubtestResultDateCreat : $CHAR16.
        AssessmentAcademicSubject : ?? BEST5.
        AssessmentLevelForWhichDesigned : ?? BEST2.
        AssessmentSubtestTitle : $CHAR65.
        AssessmentSubtestIdentifier : $CHAR42.
        TestStatus       : $CHAR11.
        TestMode         : $CHAR1.
        AssessmentSessionActualStartDate : $CHAR16.
        AssessmentSessionActualEndDateTi : $CHAR16.
        VndrTstEvent_ID  : ?? BEST8.
        AssessmentAccommodation : $CHAR4999.
        TotNbrPaused     : ?? BEST2.
        NbrPauseRet      : ?? BEST2.
        Oprtnty          : ?? BEST1.
        LanguageCode     : $CHAR3.
        EnglishLanguageProficiencyLevel : $CHAR1.
        MigrantStatus    : $CHAR3.
        FirstEntryDateIntoUSSchool : $CHAR10.
        LimitedEnglishProficiencyEntryDa : $CHAR10.
        LEPExitDate      : $CHAR10.
        TitleIIILanguageInstructionProgr : $CHAR27.
        PrimaryDisabilityType : $CHAR3.
        TestMonitorUserID : $CHAR31.
        TestMonitorSessionID : $CHAR14.
        TestMonitorEmailAddress : $CHAR48.
        Num_Itms_TOT     : ?? BEST2.
        AssessmentNumberOfItems : ?? BEST2.
        THETA_TOT        : ?? COMMA7.
        SEM_TOT_THETA    : ?? COMMA6.
        SS_TOT           : ?? BEST4.
        SEM_TOTSS        : ?? BEST3.
        Performance_Level : ?? BEST1.
        AttemptednessIndicator : $CHAR1.
        Label_SRC1       : $CHAR4.
        Num_Itms_SRC1    : ?? BEST2.
        THETA_SRC1       : ?? COMMA7.
        SEM_THETA_SRC1   : ?? COMMA6.
        SS_SRC1          : ?? BEST4.
        SEM_SRC1         : ?? BEST3.
        PL_SRC1          : ?? BEST1.
        Label_SRC2       : $CHAR4.
        Num_Itms_SRC2    : ?? BEST1.
        THETA_SRC2       : ?? COMMA7.
        SEM_THETA_SRC2   : ?? COMMA6.
        SS_SRC2          : ?? BEST4.
        SEM_SRC2         : ?? BEST3.
        PL_SRC2          : ?? BEST1.
        Label_SRC3       : $CHAR4.
        Num_Itms_SRC3    : ?? BEST1.
        THETA_SRC3       : ?? COMMA7.
        SEM_THETA_SRC3   : ?? COMMA6.
        SS_SRC3          : ?? BEST4.
        SEM_SRC3         : ?? BEST3.
        PL_SRC3          : ?? BEST1.
        Label_SRC4       : $CHAR4.
        Num_Itms_SRC4    : ?? BEST1.
        THETA_SRC4       : ?? COMMA7.
        SEM_THETA_SRC4   : ?? COMMA6.
        SS_SRC4          : ?? BEST4.
        SEM_SRC4         : ?? BEST3.
        PL_SRC4          : ?? BEST1.
        Label_SRC5       : $CHAR1.
        Num_Itms_SRC5    : $CHAR1.
        THETA_SRC5       : $CHAR1.
        SEM_THETA_SRC5   : $CHAR1.
        SS_SRC5          : $CHAR1.
        SEM_SRC5         : $CHAR1.
        PL_SRC5          : $CHAR1.
        Label_SRC6       : $CHAR1.
        Num_Itms_SRC6    : $CHAR1.
        THETA_SRC6       : $CHAR1.
        SEM_THETA_SRC6   : $CHAR1.
        SS_SRC6          : $CHAR1.
        SEM_SRC6         : $CHAR1.
        PL_SRC6          : $CHAR1.
        Paper_Barcode    : $CHAR15.
        SegmentID1       : $CHAR100.
        Accommodations_Segment1 : $CHAR1000.
        SegmentID2       : $CHAR100.
        Accommodations_Segment2 : $CHAR1000.
        SegmentID3       : $CHAR100.
        Accommodations_Segment3 : $CHAR1000.
        OppKey           : $CHAR36. ;
		**	These are to fix data defects in OR 1819 student files	** ;
		%if %eval("&ST."="OR") %then %do;
			if IDEAIndicator = 'Ye' then IDEAIndicator = 'Yes';
			if LEPStatus = 'Ye' then LEPStatus = 'Yes';
			if EconomicDisadvantageStatus = 'Ye' then EconomicDisadvantageStatus = 'Yes';
		%end;
	RUN;
%mend ReadAIRStud;
